# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: {{app}}
spec:
  image: {{image}}
  port: 8000
  liveness:
    path: arbeid/dagpenger/kalkulator/health/is-alive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
  readiness:
    path: arbeid/dagpenger/kalkulator/health/is-alive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: false
  ingresses:
    - "https://www.nav.no/arbeid/dagpenger/kalkulator"
    - "https://dp-inntekt-innsyn-ui.nais.oera.no"
  sessionAffinity: ClientIP # Sticky Session for ingress controller to prevent 404 on rollout
  env:
    - name: REACT_APP_API_URL
      value: https://www.nav.no/arbeid/dagpenger/kalkulator-api/
    - name: REACT_APP_AMPLITUDE_KEY
      value: edf391bf01b758a289ef5e7cb297f77a
