name: Build and deploy

on: [push]

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/dp-inntekt-innsyn-ui:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm --prefix ./server ci
      - run: npm run build
        env:
          CI: true
      - name: Build docker image
        run: docker build -t $IMAGE . -f Dockerfile --pull
      - name: Login to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Push Docker image
        run: docker push $IMAGE

  deploy-preprod:
    name: Deploy to Preprod
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais/dev/nais.yaml,nais/alerts.yaml
          VARS: nais/vars.yaml
          VAR: alerts_slack_channel=#team-dagpenger-alerts-non-prod
          PRINT_PAYLOAD: true
#
#  deploy-prod:
#    name: Deploy to Prod
#    needs: [build, deploy-preprod]
#    if: github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#        name: Checkout code
#      - uses: nais/deploy/actions/deploy@master
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-sbs
#          RESOURCE: nais/prod/nais.yaml,nais/alerts.yaml
#          VARS: nais/vars.yaml
#          VAR: alerts_slack_channel=#team-dagpenger-alert
#          PRINT_PAYLOAD: true
